# SPDX-License-Identifier: MIT

# Test with data generated by existing ECC implementation on OpenPGP security token
# ... and ECC implementation in pyca/cryptography

# Copyright (c) 2026 Christian Zietz <czietz@gmx.net>

import std/strutils, std/sequtils
import std/monotimes
import ecc

proc hexToSeq(hexStr: string): seq[char] =
    hexStr.split(' ').mapIt(chr(fromHex[int](it)))

let curve = newCurve(Curve_secp256r1)

# public key in uncompressed standard format
let pubkey_str = "04 2A B5 73 06 94 10 1A 98 0B 81 A6 0C 8B 65 9F 1F 07 8E A3 63 EB C3 44 0A FC A3 78 1D 5E B9 B7 C6 92 41 3A BE 31 E9 BA 45 9C E7 4D 26 13 C7 57 96 70 75 34 57 0E F4 2F 97 DE A9 9D F7 A3 0E 35 C4"
let pubkey_seq = hexToSeq(pubkey_str)

# ECDSA signature, split into 'r' and 's' values
let sig_r_str = "72 A6 BB FD 4F C8 C9 56 F5 87 E9 FF 87 41 27 1A 47 7B 16 9A 18 48 6B 51 B7 B9 C8 7C E0 25 87 D5"
let sig_s_str = "38 8A 25 7F 88 27 91 4E DB 8A 22 10 43 F7 C4 62 F2 87 5A 25 9E D5 0A 97 E6 79 04 07 B6 C5 96 9A"
let signature_seq = hexToSeq(sig_r_str) & hexToSeq(sig_s_str)

# digest
let digest_str = "00 11 22 33 44 55 66 77 88 99 aa bb cc dd ee ff 00 11 22 33 44 55 66 77 88 99 aa bb cc dd ee ff"
let digest_seq = hexToSeq(digest_str)

let pubKey = curve.loadPublicKey(pubkey_seq)
let tic = getMonoTime()
let valid  = pubKey.ecDsaVerify(digest_seq, signature_seq)
let toc = getMonoTime()

if valid:
    echo "Test vector #1 PASSED"
    echo "Verification time: ", float(toc.ticks - tic.ticks) / 1e9, " s"
else:
    echo "Test vector #1 FAILED"
    quit(1)

# public key of party 'A' in uncompressed standard format
let puba_str = "04 ec 28 16 11 18 73 d7 f0 15 a5 49 85 9f 9d 63 45 70 68 77 dc b8 7d 4a fc 26 e3 c1 d6 b6 88 26 a3 c4 6b 05 38 53 05 9a d3 ea ef 0e 80 e0 c4 c6 6f 52 52 b0 c5 2f 93 13 24 5e a0 df 89 fa 7d 6e 01"
# private key of party 'B'
let prvb_str = "8b 98 46 e2 73 52 6a 90 ba 05 47 a5 d6 03 f5 ed 36 96 1d be 15 21 86 63 87 4a 40 f6 dd f2 2f f9"
let puba = curve.loadPublicKey(hexToSeq(puba_str))
let prvb = curve.loadPrivateKey(hexToSeq(prvb_str))
# HKDF SHA-256
let tic2 = getMonoTime()
let shs = ecHMACSharedSecret(puba, prvb, info = "handshake data")
let toc2 = getMonoTime()

let expected_shs = "29 2a a3 39 dd 50 45 a5 d7 fe 4e 33 68 07 2e d0 71 ac 84 ce 3d 73 c0 ba 22 fe 42 2b 3d c7 98 6a"
let valid2 = (shs == hexToSeq(expected_shs))

if valid2:
    echo "Test vector #2 PASSED"
    echo "Shared secret derivation time: ", float(toc2.ticks - tic2.ticks) / 1e9, " s"
else:
    echo "Test vector #2 FAILED"
    quit(1)