# SPDX-License-Identifier: MIT

# Test with data generated by existing ECC implementation on OpenPGP security token

# Copyright (c) 2026 Christian Zietz <czietz@gmx.net>

import std/strutils, std/sequtils
import std/monotimes
import ecc

proc hexToSeq(hexStr: string): seq[char] =
    hexStr.split(' ').mapIt(chr(fromHex[int](it)))

let curve = newCurve(Curve_secp256r1)

# public key in uncompressed standard format
let pubkey_str = "04 2A B5 73 06 94 10 1A 98 0B 81 A6 0C 8B 65 9F 1F 07 8E A3 63 EB C3 44 0A FC A3 78 1D 5E B9 B7 C6 92 41 3A BE 31 E9 BA 45 9C E7 4D 26 13 C7 57 96 70 75 34 57 0E F4 2F 97 DE A9 9D F7 A3 0E 35 C4"
let pubkey_seq = hexToSeq(pubkey_str)

# ECDSA signature, split into 'r' and 's' values
let sig_r_str = "72 A6 BB FD 4F C8 C9 56 F5 87 E9 FF 87 41 27 1A 47 7B 16 9A 18 48 6B 51 B7 B9 C8 7C E0 25 87 D5"
let sig_s_str = "38 8A 25 7F 88 27 91 4E DB 8A 22 10 43 F7 C4 62 F2 87 5A 25 9E D5 0A 97 E6 79 04 07 B6 C5 96 9A"
let signature_seq = hexToSeq(sig_r_str) & hexToSeq(sig_s_str)

# digest
let digest_str = "00 11 22 33 44 55 66 77 88 99 aa bb cc dd ee ff 00 11 22 33 44 55 66 77 88 99 aa bb cc dd ee ff"
let digest_seq = hexToSeq(digest_str)

let pubkey = curve.loadPublicKey(pubkey_seq)
let tic = getMonoTime()
let valid  = pubKey.ecDsaVerify(digest_seq, signature_seq)
let toc = getMonoTime()

if valid:
    echo "Test vector PASSED"
    echo "Verification time: ", float(toc.ticks - tic.ticks) / 1e9, " s"
else:
    echo "Test vector FAILED"
    quit(1)