name: CI

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install Nim
        run: |
          curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH

      - name: Run the built-in self test and the test vectors
        run: |
          nim c -r ecc.nim
          nim c -r testvector.nim
          nim c -r sshcompat.nim

      - name: Check that sample code compiles without errors
        run: |
          nim c example.nim
          nim c signappl.nim
